In [ ]:
import cv2

img=cv2.imread('1006.jpg',0)
img=cv2.resize(img,(500,300))
cv2.imshow('100',img)
cv2.waitKey(0)
r = cv2.selectROI(img)
roi = img[int(r[1]):int(r[1]+r[3]), int(r[0]):int(r[0]+r[2])]
cv2.imwrite('20.jpg',roi)
cv2.imshow('roi',roi)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [61]:
import cv2
import numpy as np

image = cv2.imread("scannedimg1.jpg")
cv2.imshow('100', image)
cv2.waitKey(0)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
gray=cv2.resize(gray,(500 ,300))
template = cv2.imread('100.jpg',0)

w, h = template.shape[::-1]

result = cv2.matchTemplate(gray, template, cv2.TM_CCOEFF_NORMED)
threshold=0.53
loc=np.where(result>=threshold)

for pt in zip(*loc[::-1]): 
    cv2.rectangle(gray, pt, (pt[0] + w, pt[1] + h), (0,255,255), 2) 
    
# min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(result)

# top_left = max_loc
# bottom_right = (top_left[0] + 96, top_left[1] + 63)
# cv2.rectangle(gray, top_left, bottom_right, (0,255,255), 5)

cv2.imshow('Note', gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
roi=cv2.imread('10.jpg')
roi=cv2.resize(roi,(96,63))
cv2.imwrite('10.jpg',roi)

True

In [ ]:
print(max_loc)


In [67]:
if (result>=threshold).any==True:
    print("hello")
else:
    print("blwe")


blwe


In [63]:
result>=threshold

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [68]:
result

array([[ 0.12047864,  0.101275  ,  0.09987945, ..., -0.00634548,
         0.00437406, -0.00684515],
       [ 0.10137317,  0.09141099,  0.09673332, ..., -0.01730666,
         0.00246848, -0.00251231],
       [ 0.08581979,  0.08084188,  0.09207086, ..., -0.01424246,
         0.00733802, -0.00084033],
       ...,
       [ 0.07930759,  0.08567491,  0.07843636, ...,  0.09099656,
         0.10530688,  0.10480758],
       [ 0.07604616,  0.08602516,  0.0785683 , ...,  0.0840909 ,
         0.09619252,  0.09126608],
       [ 0.06345312,  0.07173158,  0.06717246, ...,  0.0870226 ,
         0.09889626,  0.09339148]], dtype=float32)

In [69]:
loc

(array([97], dtype=int64), array([189], dtype=int64))

In [70]:
np.where(result>=threshold)

(array([97], dtype=int64), array([189], dtype=int64))

In [72]:
zip(*loc[::-1])